clean:
	rm -f *.pyc
	rm -f *.log *.last *.loc
	rm -rf *_p0

# realclean: clean
# 	rm -rf *.flux *.image *.model *.psf *.residual

# clobber: realclean
clobber: clean
	rm -f *.enu *.cfg
	rm -f *.png *.fits
	rm -rf *ANTENNA*
	# rm -f *.pdf
	# rm -rf *.ms *.MS
	# rm -rf *_tbl *_p0

# -fin-

